name: budgify
description: A modern Flutter To-Do application with reminders, filters, and offline support.
publish_to: 'none'
version: 2.0.0+14

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  #  cupertino_icons: ^1.0.8                    # For using Cupertino icons
  flutter_icon_snackbar: ^1.1.4              # For showing animated snackbar with icons
  icons_launcher: ^3.0.0                     # For setting app launcher icon in ios and android
  font_awesome_flutter: ^10.5.0              # For using More icons
  google_fonts: 6.2.1                        # For using Google Fonts
  flutter_native_splash: ^2.4.4              # For setting splash screen
  url_launcher: ^6.3.1                       # For launching URLs
  #  flutter_carousel_widget: ^3.1.0            # For using carousel widget
  share_plus: ^10.1.4                        # For sharing content
  flutter_riverpod: ^2.6.1                   # For state management
  salomon_bottom_bar: ^3.3.2                 # For using salomon bottom bar
  # table_calendar: ^3.2.0                     # For using table calendar
  syncfusion_flutter_datepicker: ^29.1.38     # For using date picker

  ###Local Database
  sqflite: ^2.4.2                            # For using SQLite database
  path_provider: ^2.1.5                      # For getting path to the database
  path: ^1.9.1                               # For using path
  shared_preferences: ^2.5.2                 # For storing key-value pairs

  ###Showing Charts
  fl_chart: ^0.71.0                          # For using charts
  syncfusion_flutter_charts: ^29.1.38        # For using charts
  #  flutter_plot: ^0.1.0                       # For using charts

  dropdown_button2: ^2.3.9                   # For using dropdown button
  currency_picker: ^2.0.21                   # For using currency picker
  scroll_date_picker: ^3.8.0                 # For using scroll date picker
  intl: ^0.20.2                              # For using date and time formatting
  flutter_rating_bar: ^4.0.1                  # For using rating bar
  carousel_slider: ^5.0.0                    # For using carousel slider

  google_mobile_ads: ^5.3.1                  # For showing ads
  flutter_inappwebview: ^6.1.5                # For using in-app webview
  equatable: ^2.0.7
  flutter_staggered_grid_view: ^0.7.0
  android_intent_plus: ^6.0.0
  permission_handler: ^12.0.1
  flutter_local_notifications: ^19.5.0
  android_alarm_manager_plus: ^5.0.0
  logger: ^2.6.2

  #Firebase
  firebase_core: ^3.4.0                      # For initializing Firebase
  firebase_crashlytics: any                  # For crash reporting
  firebase_analytics: any                    # For analytics

#  flutter_date_pickers: ^0.4.3               # For using date picker
#  change_app_package_name: ^1.5.0            # For changing app package name

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/icons/my_app_icons/
    - assets/icons/category/
    - assets/images/
    - assets/images/onboard/
    - assets/icons/splash/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf

icons_launcher:
  image_path: "assets/icons/my_app_icons/budget_flow_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_maskable: true
  platforms:
    android:
      enable: true
    ios:
      enable: true

flutter_native_splash:
  color: "#F5F5F5"
  image: assets/icons/splash/splash_before_android_12.png
  branding: assets/icons/splash/mysterious_coder_branding_icon.png
  #  color_dark: "#000000"
  #  image_dark: assets/icons/splash_screen.jpg
  android: true
  ios: true
  android_12:
    color: "#F5F5F5"
    image: assets/icons/splash/splash_screen_icon.png
    branding: assets/icons/splash/mysterious_coder_branding_icon.png
#    color_dark: "#000000"
#    image_dark: assets/icons/splash_screen.jpg
